### ISSUE TITLE
Allow export/import

### ISSUE THREAD

**Issue by Finkregh** [blockbasti/just_another_workout_timer#80] opened 2021-08-01 09:17 UTC
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
Export workouts to file, eg json, then I could share it with friends. 
Also import of course ;)

**Comment by blockbasti** [comment] 2021-08-02 07:49
Duplicate of #49

**Closed by blockbasti** 2021-08-02 07:49 UTC
Labels: enhancement
