### ISSUE TITLE
Export/import feature

### ISSUE THREAD

**Issue by madduck** [blockbasti/just_another_workout_timer#87] opened 2021-08-29 05:44 UTC
I'd like to recommend this app to the other member in our club, and ideally be able to publish the workouts for download. Would it be possible to export a workout to e.g. JSON, so that it can be imported by another user?

**Comment by blockbasti** [comment] 2021-08-29 08:54
Duplicate of #49

**Closed by blockbasti** 2021-08-29 08:54 UTC
Labels: enhancement

**Comment by madduck** [comment] 2021-08-29 09:54
I am sorry for forgetting to check issues on this one.
